# Generated by Django 4.0 on 2022-01-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_commment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commment',
            new_name='Comment',
        ),
    ]
